# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [ ]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [ ]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [1]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [2]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x6000033b82a0
byteorder:  little
byteswap:  False
type: int64


In [3]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [5]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10)
print(arr)
arr.shape

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


(50,)

In [6]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.57136541 0.20831508 0.77822969]
 [0.08933034 0.45962375 0.53218429]
 [0.53204963 0.22731869 0.57403062]]


In [7]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [8]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.57136541 0.20831508 0.77822969]
 [0.08933034 0.45962375 0.53218429]
 [0.53204963 0.22731869 0.57403062]]
...
float64
(3, 3)
3
2
9
8
72


In [9]:
arr.__sizeof__()

200

### ЗАВДАННЯ 1

In [ ]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = ...
print(arr1_1)

In [ ]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = ...
print(arr1_2)

In [ ]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = ...
print(arr1_3)

## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [12]:
# створити 2-мірний float-масив (5x2) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok, dtype='int').reshape(5,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int64


In [14]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float32')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float32


In [15]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [ ]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = ...
...
print(arr2_1)

In [ ]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = ...
...
print(arr2_2)

In [ ]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = ...
...
print(arr2_3)

## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [17]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-2])

[10  6  7 21 44]
10
7
21


In [18]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[29 19 31 34]
 [21 28 43 43]
 [35 47 40 24]
 [33 39 38 28]]


In [20]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -3]
print(el)

28


In [21]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[33 39 38 28]


In [22]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[29 19 31 34]
 [21 28 43 43]]


In [23]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[19 31]
 [28 43]
 [47 40]
 [39 38]]


In [24]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[29 19 31 34]
 [35 47 40 24]]


In [25]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[29 31 34 21 28 43 43 35 47 40 24 33 39 38 28]


### ЗАВДАННЯ 3

In [ ]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = ...

In [ ]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = ...
print(el3_2)

In [ ]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = ...
print(vect3_3)

In [ ]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = ...
print(vect3_4)

In [ ]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = ...
print(mat3_5)

## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [26]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [30]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.29153539 0.10078629 0.43145295 0.08480192 0.75585275]
 [0.12157748 0.64323319 0.23062242 0.61792606 0.12787736]
 [0.33184704 0.81685896 0.98722642 0.36235778 0.09931431]
 [0.07504962 0.28347427 0.99495295 0.80787833 0.50609872]
 [0.06095394 0.661523   0.87009007 0.72301178 0.94495128]]
...
[0.29153539 0.64323319 0.98722642 0.80787833 0.94495128]


In [33]:
type(mat.T)

numpy.ndarray

In [34]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.29153539 0.12157748 0.33184704 0.07504962 0.06095394]
 [0.10078629 0.64323319 0.81685896 0.28347427 0.661523  ]
 [0.43145295 0.23062242 0.98722642 0.99495295 0.87009007]
 [0.08480192 0.61792606 0.36235778 0.80787833 0.72301178]
 [0.75585275 0.12787736 0.09931431 0.50609872 0.94495128]]


In [35]:
type(mT)

numpy.ndarray

In [36]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

0.10919571525901071


In [37]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[ 2.81749209  2.02847161  0.17622616  0.67767682 -2.90965045]
 [-0.70292456  0.18601715  0.65514266 -1.50070884  1.27198289]
 [-0.51594299 -1.39929668  0.79625379  0.58266832  0.20630504]
 [ 0.24640646  1.5864056  -0.90871859  1.32361548 -1.02517848]
 [ 0.59688328 -0.18643686 -0.50789061 -0.54237418  0.94991233]]


### ЗАВАДАННЯ 4

In [ ]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = ...
print(mat4_1)

In [ ]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = ...
print(diag4_2)

In [ ]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = ...
print(trans4_3)

In [ ]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = ...

## 5. Операції над масивами

### ПРИКЛАДИ

In [38]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])
vect

array([ 1,  3,  2, -3,  5,  0])

In [39]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
s, m, vs, mid

(8, -3, array([-3,  0,  1,  2,  3,  5]), 1.3333333333333333)

In [40]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [41]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=1)
print(s)

[  6   8 231]


In [42]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [43]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [48]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,4]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 4]]


In [49]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [50]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


/var/folders/4v/ry8_tdjn3mbfw2gn4jk97nt40000gp/T/ipykernel_53096/3347190385.py:2: RuntimeWarning: divide by zero encountered in divide
  K = N / M


In [51]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [43 29 27]]


In [52]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 39531  24928  27144]
 [ 79062  49856  54288]
 [134670  84973  92403]]


In [53]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [54]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [ ]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

In [55]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[2 3 7 9 6]
[2 3 7 9 6]
4458617072 4458617072
[2 3 7 9 6]
4458617072 4435687440


In [56]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [ ]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = ...
sum_mat5_1 = ...
print(sum_mat5_1)

In [ ]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = ...
print(min_mat5_1)

In [ ]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = ...
print(mat5_3)

In [ ]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = ...
print(mat5_4)

In [ ]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = ...
...