#  Лабораторна робота "Обробка табличних даних засобами бібліотеки Pandas"

__Метою__ лабораторної роботи є вивчення технологій первинного аналізу даних в середовищі бібліотеки Pandas, а саме здобуття навичок:
- працювати з даними використовуючи мову Python та пакет Pandas
- робити передобробку даних
- знаходити прості закономірності у даних

In [2]:
# підключити бібліотеки Pandas та NumPy
import pandas as pd
import numpy as np

## 1. Створення  DataFrame

__DataFrame__ — це двовимірна неоднорідна таблична структура даних із змінюваними розмірами з іменованими вісями (рядками та стовпцями)

### ПРИКЛАДИ

In [3]:
# створити DataFrame з 1 колонкою з python-списка
df = pd.DataFrame(["Петя", "Вася", "Микола"])
print(df)
print(type(df))

        0
0    Петя
1    Вася
2  Микола
<class 'pandas.core.frame.DataFrame'>


In [4]:
# створити DataFrame з np-матриці розміром 10х10 випадкових чисел
mat = np.random.randint(100, 500, (10,10), dtype="int16")
print(mat)
df = pd.DataFrame(mat)
df

[[453 333 173 285 496 452 215 490 386 260]
 [470 274 303 304 302 169 104 141 269 381]
 [175 379 262 376 228 475 106 460 377 297]
 [218 413 189 223 392 477 284 203 170 229]
 [404 297 145 330 263 480 308 450 479 168]
 [266 474 332 255 214 477 248 134 128 446]
 [230 361 337 298 159 230 425 282 338 322]
 [498 151 318 155 294 358 351 384 219 133]
 [464 248 383 341 356 468 190 221 350 484]
 [406 196 261 173 124 308 199 162 215 138]]


0    1    2    3    4    5    6    7    8    9
0  453  333  173  285  496  452  215  490  386  260
1  470  274  303  304  302  169  104  141  269  381
2  175  379  262  376  228  475  106  460  377  297
3  218  413  189  223  392  477  284  203  170  229
4  404  297  145  330  263  480  308  450  479  168
5  266  474  332  255  214  477  248  134  128  446
6  230  361  337  298  159  230  425  282  338  322
7  498  151  318  155  294  358  351  384  219  133
8  464  248  383  341  356  468  190  221  350  484
9  406  196  261  173  124  308  199  162  215  138

In [5]:
# створити DataFrame з 2-мірного випадкового масиву з іменованими колонками
arr = np.random.random((5,3))
print(arr)
df = pd.DataFrame(arr, columns=["колонка 1", "колонка 2", "колонка 3"])
df

[[0.84466985 0.34031919 0.02029073]
 [0.9267947  0.64723768 0.36845647]
 [0.12490231 0.97915135 0.47180942]
 [0.7927944  0.23977645 0.23383545]
 [0.95101866 0.83082502 0.86170461]]


колонка 1  колонка 2  колонка 3
0   0.844670   0.340319   0.020291
1   0.926795   0.647238   0.368456
2   0.124902   0.979151   0.471809
3   0.792794   0.239776   0.233835
4   0.951019   0.830825   0.861705

In [6]:
# створити DataFrame з python-словника в якому ключ - це ім'я, а значення - 
# це масив з 5-ти випадкових чисел з модифікованими індексами рядків
d = {
    "Петя": np.random.random(5),
    "Вася" : np.random.random(5),
    "Микола":np.random.random(5)
    }
a = pd.DataFrame(d, index=[10,20,30,40,50])

In [7]:
a

Петя      Вася    Микола
10  0.374650  0.805686  0.411404
20  0.223748  0.919716  0.021624
30  0.598573  0.418195  0.003396
40  0.216880  0.516705  0.983924
50  0.811565  0.575016  0.897634

In [8]:
# створити dataFrame з ітеруємого об'єкта
name = ["Вася", "Петя", "Микола"]
rik = [2001, 2000, 2003]
name_rik = list(zip(name, rik))
print(name_rik)
df = pd.DataFrame(name_rik, columns=["Ім'я", "Рік народження"])
df

[('Вася', 2001), ('Петя', 2000), ('Микола', 2003)]


Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

In [9]:
pd.read_csv?

In [12]:
!echo "Вася, 2001\nПетя, 2000\nМикола,2003\n" > file.csv
!cat file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv("file.csv", names=["Ім'я", "Рік народження"])
df

Вася, 2001
Петя, 2000
Микола,2003



Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

### ЗАВДАННЯ

In [ ]:
# ЗАВДАННЯ 1.1: створити датафрейм з списку 10-ти простих чисел
df1_1 = ...

In [ ]:
# ЗАВДАННЯ 1.2: створити датафрейм з матриці 5х6 випадкових чисел з плаваючою точкою
df1_2 = ...

ЗАВДАННЯ 1.3: створити  DataFrame наступного вигляду:

|ім'я | прізвище| рік народження | телефон
|:-----|:------|:-----:|:-------:
|Петро| Петров| 2000| 222-222-2222
|Іван| Іванов| 2002| 333-333-3333
|Степан| Степанов| 2001| 444-444-4444

In [ ]:
df1_3 = ...

In [ ]:
# ЗАВДАННЯ 1.4: створити датафрейм з 20 перших рядків excel-файлу, 
# який розташовано за адресою: 
# https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls
df1_4 = ...

## 2. Інспектування DataFrame

__Інспектування__ - це процедури вивчення внутрішньої структури даних та вмісту датафрейма

### ПРИКЛАДИ

In [13]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [21]:
# отримати загальну інформацію про датасет
a = titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [15]:
# вивести перші 3 рядкі
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [16]:
# вивести останні 2 рядки
titanic.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

In [17]:
# отримати імена колонок
col_names = titanic.columns
print(col_names)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [18]:
# вивести загальну статистику датасету - числові поля
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [20]:
# вивести статитсику текстового поля `Sex` 
titanic[['Sex', 'Name']].describe()

Sex                     Name
count    891                      891
unique     2                      891
top     male  Braund, Mr. Owen Harris
freq     577                        1

In [ ]:
# перевірити тип колонки датасету
type(titanic['Age'])

In [ ]:
# вивести перші 10 рядків деяких колонок
cols = ["Name", "Age", "Sex"]
titanic[cols].head(10)

In [ ]:
# вивести рядки з 100 по 110
titanic[100:110]

In [ ]:
# вивести тільки чоловіків
cond = titanic["Sex"] == "male"
titanic[cond]

In [ ]:
# вивести рядки в яких пропущено значення поля `Age`
cond = titanic['Age'].isna()
titanic[cond].head(3)

In [23]:
# вивести рядки з пасажирами вік яких з 30 до 50 років
cond = titanic['Age'].between(30, 50)
titanic[cond]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
13            14         0       3   
18            19         0       3   
..           ...       ...     ...   
872          873         0       1   
873          874         0       3   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
..                                                 ...     ...   ...    ...   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
4        0    373450   8.0500          NaN        S  
13       5    347082  31.2750          NaN        S  
18       0    345763  18.0000          NaN        S  
..     ...       ...      ...          ...      ...  
872      0       695   5.0000  B51 B53 B55        S  
873      0    345765   9.0000          NaN        S  
881      0    349257   7.8958          NaN        S  
885      5    382652  29.1250          NaN        Q  
890      0    370376   7.7500          NaN        Q  

[266 rows x 12 columns]

### ЗАВДАННЯ

In [ ]:
# ЗАВДАННЯ 2.1: вивести характеристики датасету `titanic`
...

In [ ]:
# ЗАВДАННЯ 2.2: вивести статистичні параметри полів `Age` та `Fare` датасету `titanic`
...

In [ ]:
# ЗАВДАННЯ 2.3: пірахувати кількість записів в яких заповнені усі показчики
...

In [ ]:
# ЗАВДАННЯ 2.4: пірахувати кількість виживших (survived=1) пасажирів жиночої статі (Sex=`female`)
...

## 3. Перетворення датафреймів

__Перетворення__ - це сукупність операцій та методів для зміни структури та вмісту датафрейму та окремих його елементів

### ПРИКЛАДИ

In [24]:
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}

df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [25]:
# типи колонок та елементів в колонці
print(df["рейтинг"].dtype)
print(type(df['рейтинг']))

object
<class 'pandas.core.series.Series'>


In [27]:
# Перетворити тип колонки (показчика) 'рейтинг' в ціле числове
df['рейтинг'] = df['рейтинг'].astype("int8")
print(df["рейтинг"].dtype)

int8


In [32]:
# додати колонку "адреса"
df["адреса"] = ["Київ", "Бровари", "Фастів"]
df

ім'я  вік  рейтинг   адреса
0  Петя   22       10     Київ
1  Вася  200        3  Бровари
2  Галя   21        2   Фастів

In [33]:
#  збільшити значення "рейтинг" на 3
df['рейтинг'] = df['рейтинг'] + 3
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася  200        6  Бровари
2  Галя   21        5   Фастів

In [34]:
# виправити значення параметру 'вік' для імені 'Вася'
df.loc[1, "вік"] = 20
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася   20        6  Бровари
2  Галя   21        5   Фастів

In [36]:
# видалити колонку `вік'
df.drop(columns='вік', inplace=True)
df

ім'я  рейтинг   адреса
0  Петя       13     Київ
1  Вася        6  Бровари
2  Галя        5   Фастів

In [37]:
# вивести 5 перших рядків датафрейму
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [39]:
# вивести 3 випадкових рядки датафрейму
titanic.sample(39)

PassengerId  Survived  Pclass  \
429          430         1       3   
808          809         0       2   
829          830         1       1   
240          241         0       3   
97            98         1       1   
556          557         1       1   
471          472         0       3   
705          706         0       2   
75            76         0       3   
271          272         1       3   
682          683         0       3   
497          498         0       3   
608          609         1       2   
506          507         1       2   
27            28         0       1   
278          279         0       3   
289          290         1       3   
475          476         0       1   
456          457         0       1   
442          443         0       3   
248          249         1       1   
188          189         0       3   
410          411         0       3   
218          219         1       1   
140          141         0       3   
888          889         0       3   
290          291         1       1   
540          541         1       1   
703          704         0       3   
294          295         0       3   
104          105         0       3   
827          828         1       2   
719          720         0       3   
183          184         1       2   
511          512         0       3   
308          309         0       2   
596          597         1       2   
760          761         0       3   
124          125         0       1   

                                                  Name     Sex   Age  SibSp  \
429                 Pickard, Mr. Berk (Berk Trembisky)    male  32.0      0   
808                                  Meyer, Mr. August    male  39.0      0   
829          Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   
240                              Zabour, Miss. Thamine  female   NaN      1   
97                     Greenfield, Mr. William Bertram    male  23.0      0   
556  Duff Gordon, Lady. (Lucille Christiana Sutherl...  female  48.0      1   
471                                    Cacic, Mr. Luka    male  38.0      0   
705     Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0      0   
75                             Moen, Mr. Sigurd Hansen    male  25.0      0   
271                       Tornquist, Mr. William Henry    male  25.0      0   
682                        Olsvigen, Mr. Thor Anderson    male  20.0      0   
497                    Shellard, Mr. Frederick William    male   NaN      0   
608  Laroche, Mrs. Joseph (Juliette Marie Louise La...  female  22.0      1   
506      Quick, Mrs. Frederick Charles (Jane Richards)  female  33.0      0   
27                      Fortune, Mr. Charles Alexander    male  19.0      3   
278                                 Rice, Master. Eric    male   7.0      4   
289                               Connolly, Miss. Kate  female  22.0      0   
475                        Clifford, Mr. George Quincy    male   NaN      0   
456                          Millet, Mr. Francis Davis    male  65.0      0   
442                          Petterson, Mr. Johan Emil    male  25.0      1   
248                      Beckwith, Mr. Richard Leonard    male  37.0      1   
188                                   Bourke, Mr. John    male  40.0      1   
410                                 Sdycoff, Mr. Todor    male   NaN      0   
218                              Bazzani, Miss. Albina  female  32.0      0   
140                      Boulos, Mrs. Joseph (Sultana)  female   NaN      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
290                       Barber, Miss. Ellen "Nellie"  female  26.0      0   
540                            Crosby, Miss. Harriet R  female  36.0      0   
703                              Gallagher, Mr. Martin    male  25.0      0   
294                                   Mineff, Mr. Ivan    male  24.0      0   
104                     Gustafsson,

In [ ]:
# відсортувати dataframe `titanic` за віком пасажиров
titanic.sort_values(['Age'])

In [40]:
# перейменувати значення в `Embarked` стовпчику:
# С - Cherbourg
# Q - Queenstown
# S - Southampton
titanic['Embarked'].replace({"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"},
                           inplace=True)
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin     Embarked  
0        0         A/5 21171   7.2500   NaN  Southampton  
1        0          PC 17599  71.2833   C85    Cherbourg  
2        0  STON/O2. 3101282   7.9250   NaN  Southampton  
3        0            113803  53.1000  C123  Southampton  
4        0            373450   8.0500   NaN  Southampton  
..     ...               ...      ...   ...          ...  
886      0            211536  13.0000   NaN  Southampton  
887      0            112053  30.0000   B42  Southampton  
888      2        W./C. 6607  23.4500   NaN  Southampton  
889      0            111369  30.0000  C148    Cherbourg  
890      0            370376   7.7500   NaN   Queenstown  

[891 rows x 12 columns]

In [41]:
# підрахувати кількість пасажирів 1-го класу (Pclass=1)
cond = titanic['Pclass'] == 1
kol_pass = titanic[cond]['PassengerId'].count()
kol_pass

216

In [42]:
# замінити відсутні номери кают на ''
titanic.fillna({"Cabin": "***"}, inplace=True)
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin     Embarked  
0      0         A/5 21171   7.2500   ***  Southampton  
1      0          PC 17599  71.2833   C85    Cherbourg  
2      0  STON/O2. 3101282   7.9250   ***  Southampton

In [43]:
# видалити рядки в яких є відсутні значення 
titanic.dropna(axis=0, how='any', inplace=True)
titanic.shape

(712, 12)

### ЗАВДАННЯ

In [ ]:
# ЗАВДАННЯ 3.1: створити датафрейм з словника d
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}
df = ...

In [ ]:
# ЗАВДАННЯ 3.2: додати до `df` стовбчик з показчиком 
# `рік завершення школи` = [2018, 2020, 200]
...
print(df)

In [ ]:
# ЗАВДАННЯ 3.3: виправити 'рік завершення школи' з 200 на 2020
...
print(df)

In [ ]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [ ]:
# ЗАВДАННЯ 3.4: вивести з датасету `titanic` останні 10 записів 
...

In [ ]:
# ЗАВДАННЯ 3.5: вибрати з датасету `titanic` рядки з пасажирами чоловічої статі віком 
# від 20 до 30 років, які подорожували 2 класом
...

In [ ]:
# ЗАВДАННЯ 3.6: видалити з датасету `titanic` рядки з пасажирами у яких відсутня
# вартість (fare) квітка
df = ...
df

In [ ]:
# ЗАВДАННЯ 3.7: підрахувати середню вартість квитка у каютах 1-го класу
avg_price = ...
print(avg_price)

## 4. Агрегація датафреймів

__Агрегація__ - це функції отримання агрегованих даних шляхом групування об'єктів датафрейма 

### ПРИКЛАДИ

In [ ]:
titanic.head(3)

In [44]:
# підрахувати середній вік пасажирів по класам кают
group_by_class = titanic.groupby(["Pclass"])
avg_age = group_by_class["Age"].mean()
print(avg_age)

Pclass
1    38.105543
2    29.877630
3    25.140620
Name: Age, dtype: float64


In [45]:
# підрахувати кількість чоловіків та жінок по класам кают
man_woman_count = titanic.groupby(["Pclass", "Sex"])["Sex"].count()
man_woman_count

Pclass  Sex   
1       female     83
        male      101
2       female     74
        male       99
3       female    102
        male      253
Name: Sex, dtype: int64

In [46]:
type(man_woman_count)

pandas.core.series.Series

In [ ]:
# створити таблицю в якій підраховано середню вартість білетів (Fare) в залежності
# від місця посадки (Embarked) по класам кают
tickets_cost = titanic.pivot_table(values="Fare", index="Pclass", columns="Embarked",
                   aggfunc=np.mean)
tickets_cost

In [47]:
import pivottablejs

### ЗАВДАННЯ

In [ ]:
# ЗАВДАННЯ 4.1: отримати відомості про максимальний вік жінок та чоловіків
max_age = ...
print(max_age)

___ЗАВДАННЯ 4.2___

на основі даних з `titanic` побудувати таблицю наступного вигляду:

Pclass  |Male  | Female
--------|------|-------
1  | ... | ...
2  | ... | ...
3  | ... | ...

де замість `...` повинно бути кількість виживших (Survived) чоловіків та жінок відповідно

In [ ]:
surv_table = ...
surv_table